(ns testing.gary
    (:gen-class)
    (:require [seesaw.graphics :as graph]
              [testing.images :as pics])
)

;Definition of pictures
(def background (pics/load-image "backgr.png"))
(def road (pics/load-image "board.png"))
(def control (pics/load-image-scale-by-factor "contr2d.png" 0.02))
(def rock (pics/load-image-scale-by-factor "rock.png" 0.05))
(def control2 (pics/load-image-scale-by-factor "contr2d.png" 0.6))
(def obst (pics/load-image "obst.png"))
;(def runner (pics/load-image-scale-by-factor "runner.png" 0.06))
(def snail (pics/load-image-scale-by-factor "snail copy.png" 0.2))
(def gx (atom 1000))
(def gx-c (atom 1200))
(def gx-2 (atom 1000))
(def gx-3 (atom 0))
(def gx-4 (atom 1400))
(def gx-5 (atom 1800))
(def x (atom 40))
(def ran (atom (+ (rand-int 150) 400)))
(def ranC (atom (+ (rand-int 150) 400)))
(def ran2 (atom (+ (rand-int 150) 400)))
(def ran3 (atom (+ (rand-int 150) 400)))
(def dist_between_controls (atom 300))
(def dx (atom 450))
(def dy (atom 450))

(defn add [a b]
  (+ a b))

;:Drawing loop
(defn draw-it
    [gr]
    (swap! gx dec)
    (swap! gx-c dec)
    (swap! gx-2 dec)
    (swap! gx-3 dec)
    (swap! gx-4 dec)
    (swap! gx-5 dec)
    (if (= @gx-2 -50)
        (reset! gx-2 1000))
    (if (= @gx-c -50)
        (reset! gx-c 1000))
    (if (= @gx-5 -50)
        (reset! gx-5 1000))
    (if (= @gx-4 -50)
        (reset! gx-4 1000))
    (if (= @gx-3 -1000)
        (reset! gx-3 1000))
    (if (= @gx -1000)
        (reset! gx 1000)
    )
    (pics/draw-image background gr 0 0)
    (pics/draw-image road gr (deref gx-3) 0)
    (pics/draw-image road gr (deref gx) 0)
    ;(pics/draw-image runner gr 450 450)
    (pics/draw-image snail gr (deref dx) (deref dy))
;:    (if (key == KeyEvent.VK_UP) 
;:        (swap! dy dec)
;:    )

;:Reseting and regenerating the random numbers for positioning blocks and stars
    (if (> @gx-2 999)
        (reset! ran (+ (rand-int 150) 400))
    )
     (if (> @gx-c 999)
        (reset! ranC (+ (rand-int 150) 400))
    )
    (if (> @gx-4 999)
        (reset! ran2 (+ (rand-int 150) 400))
    )
    (if (> @gx-5 999)
        (reset! ran3 (+ (rand-int 150) 400))
    )
    (pics/draw-image rock gr (deref gx-2) (deref ran))
    (pics/draw-image rock gr (deref gx-4) (deref ran2))
    (pics/draw-image rock gr (deref gx-5) (deref ran3))
    (pics/draw-image control2 gr (deref gx-c) 385)
)


